name: 'etl_pipeline'
version: '1.0.0'
config-version: 2

profile: 'etl_pipeline'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

on-run-start:
  - '{{ log_project_start() }}'

models:
  etl_pipeline:
    +materialized: view
    +post-hook:
      - '{{ log_row_count() }}'
    staging:
      +materialized: view
      +schema: staging
    marts:
      dimensions:
        +materialized: view
        +schema: dest
      facts:
        +materialized: view
        +schema: dest
